### ISSUE TITLE
i am enthusiast with low level programming and i want your help

### ISSUE THREAD

**Issue by Androvian** [pwk4m1/TinyBIOS#1]
i wanted to know is there any good resources to learn bios development also to learn assembly x86

**Comment by pwk4m1** [comment]
Hi Androvian 

I'm more than happy to help, however I think git issues are a bit challenging
place for discussions about how to learn stuff & so forth. So for future 
reference: please email instead (:

I've compiled a small list of links below, that I believe to be beneficial
for learning more about how to go on with assembly, bioses, firmware, and
computer science in general.

If you have any further questions, please send me email to
k4m1@protonmail.com

Links:
	https://cs.lmu.edu/~ray/notes/nasmtutorial/
	Tutorial for nasm assembly

	https://wiki.osdev.org/Expanded_Main_Page
	This wiki is technically about operating system development, but 
	lots of the same things apply for bios development aswell

	https://www.coreboot.org/ 
	Site of coreboot, open source bios project,
	lots of useful knowledge, links, and overall data there

	https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html
	Intels programming/software development manuals, useful for when
	one has to figure out how intel CPUs expect things to be set up,
	etc.

	https://pwk4m1.github.io/reset.html
	Shameless self-advertisement here, but a small 'tutorial' on how
	to write a "hello world" 'firmware' for qemu

	https://www.amd.com/system/files/TechDocs/43366.pdf
	Specific bios development guide for AMD SB700/710/750, which
	might not be super-useful but still nice document to look for ideas on
	how to approach different problems

	https://www.bios-mods.com/forum/Forum-Bios-Mods-Forum
	Forum for bios modding, not exactly the 'bios from scratch' approach
	but does contain a *lot* of useful information
