### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by kernelguardian** [pwk4m1/TinyBIOS#2]
Running make threw this error

```
rm -rf bin/bios
nasm  -o bin/bios src/reset.asm
make: nasm: No such file or directory
make: *** [build] Error 1
```

**Comment by Mylloon** [comment]
Looks like [nasm](https://nasm.us/) is a dependency you need

**Comment by pwk4m1** [comment]
Yes, I should make a dependency list somewhere I suppose, or set up the makefile in a way where it more clearly tells the issue. Thanks @Mylloon for quick reply here
